### ISSUE TITLE
/IW:0x3/0/TextClouds is Part of Export with Unchanged Default Value

### ISSUE THREAD

**Issue by cornelius-koepp** [cornelius-koepp/OFM-ConfigTransfer#21]
# Reproduce
1. Import ETS-App with Module **IW** (Version 0.3.0 [02270d07d716eaf4593cb54ec038ac4f823ddf09](https://github.com/OpenKNX/OFM-InternetWeatherModule/tree/02270d07d716eaf4593cb54ec038ac4f823ddf09)) 
2. Export IW with Channel 0 included (Default Export Configuration of UCT>=0.3)
3. Result is `OpenKNX,cv1,0xAFC0:0x2B/IW:0x3/0§TextClouds=Wolken%20XXX%25§;OpenKNX`, but expected `OpenKNX,cv1,0xAFC0:0x2B/IW:0x3/0§;OpenKNX` (without Parameter TextClouds)

# Affected UCT Version
Confirmed in local development environment 8c58c5c2f970c8a1979e81bc743aad69aab44198
* [x] Check other Versions
  * [x] 0.1 (Released)
  * [x] 0.2 (Released)
  * [x] 0.3 (Current DEV state on v1dev)

# Analysis
* [x] Confirm first hypothesis: Params with `%` in default value are not handled correctly

## Result
OpenKNXproducer 3.3.4.0 does not include Default-Values including `%`, see Issue https://github.com/OpenKNX/OpenKNXproducer/issues/15

# TODOs
* [x]  Investigate side effects by change in producer
* [x] Check need of conceptual updates
* [ ] Define migration path for changing default output of producer, see also #12

**Comment by cornelius-koepp** [comment]
Fixed in Producer Release [v3.3.12](https://github.com/OpenKNX/OpenKNXproducer/releases/tag/v3.3.12) 
* [x] Udate minimal Producer Version in Documentation

**Comment by cornelius-koepp** [comment]
Minimal Producer Version Noted in 1981f206e9f464fcec1d580db63e168666aa181f
